sudo: false
dist: trusty
language: erlang
otp_release:
  - 20.0.1
before_install:
  - if test osx = "${TRAVIS_OS_NAME:?}"; then export HOMEBREW_CACHE="$HOME/Library/Caches/Homebrew"; fi
  - if test osx = "${TRAVIS_OS_NAME:?}"; then brew update; fi
  - if test osx = "${TRAVIS_OS_NAME:?}"; then brew install erlang && export PATH="$(brew --prefix erlang)"/bin:"$PATH"; fi
  - erl -version
  - epmd -daemon
  - ./ci before_install "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
install:
  - ./ci install "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
script:
  - ./ci script "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
after_failure:
  - ./ci after_failure "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
deploy:
  provider: releases
  api_key:
    # See https://docs.travis-ci.com/user/deployment/releases/#Authenticating-with-an-OAuth-token
    secure: IHm/uQSPvITBzKwHlTx8+MQBZSxOlOgKbYmznfbjW1L9LRB8s3Lu1GhmGX5QdQL0O/+irCuSd7H1N+xkg7CFeTOxgg/Jvxir5ztmhDQYYuCkwlUB4/NR6IMNMzGfdZGWcQHfSZQv9o0/jaQfH9lKJxKKip5HsH9n+QCWcT2tftwz2qFvcmY2zHaji123tQNuClKfUoJrTj37M3IUWA3+czr+SPgfgcWfAE+pXCpKR5BLV7SMZrk5SE/hCyCwDaTvC1DfYvSbxXRUcCCcFkZw7B/xWHvHM6kAxwyw/Qh/UWisIkI0TeKAX1wX+OLm08bMqK8YRnYIjikLqi/9XjKPe5PlBPfRoLX8K+CuX1iW175KmJkI1r+E0rnzaPGbN9iMHNNbawWxmg1kb5+lmSaa9loKEnbM6fcLcneWSR3yVLIsWA+w30+5bfythMFpuOSsfmc8GJpbenI12m42HcowzVrTH1cA4EL47C9EZca8DzoSKJdDEqjvzT2mMZUsDODcHoOSJ+s9oYAYc8aU4NuIaSO7QIawtrmnmIw/xDVWCpLedSyLiXKHKlD3UzmidYAfM3xZiDM+MUEbI6cQpic3ZuItud7NWGZbOMr14aBEvsposugGv6pzKegh1fKIWX37DnP3eZXfHEolny4d24scG2yN54ZG75o0wJI7hBQWGT8=
  file_glob: true
  file: _build/prod/rel/epoch/epoch-*-*.tar.gz
  skip_cleanup: true
  on:
    # See https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
    repo: velzevur/epoch
    tags: true
    all_branches: true # Workaround for Travis - see https://github.com/travis-ci/travis-ci/issues/1675#issuecomment-37851765
    condition: "${JOB:?} = package"
matrix:
  include:
    - os: osx
      osx_image: xcode8.3 # [`xcode8.3` is Xcode 8.3.3 on OS X 10.12](https://docs.travis-ci.com/user/reference/osx#OS-X-Version)
      language: generic
      env: JOB=package
    - if: tag IS present # additional JOB to run the release acceptance test for releases only
      env: JOB=acceptance-test
    - if: tag IS present # additional JOB to run the release acceptance test for releases only
      env: JOB=acceptance-test
      os: osx
      osx_image: xcode8.3 # [`xcode8.3` is Xcode 8.3.3 on OS X 10.12](https://docs.travis-ci.com/user/reference/osx#OS-X-Version)
      language: generic
  allow_failures:
    - env: JOB=xref
  fast_finish: true
env:
  - JOB=test
  - JOB=dialyzer
  - JOB=xref
  - JOB=check_rels
  - JOB=package
cache:
  directories:
    - $HOME/.cache/rebar3
    - $HOME/Library/Caches/Homebrew
